version: '3.4'
services:
  web:
    container_name: epam_music_web_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - pgadmin
      - redis
    volumes:
      - .:/app
#      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
  postgres:
    image: postgres:15.4
    container_name: epam_music_postgres_container
    restart: always
    environment:
      POSTGRES_USER: <%= Rails.application.credentials.development[:postgres_user] %>
      POSTGRES_PASSWORD: <%= Rails.application.credentials.development[:postgres_password] %>
      POSTGRES_DB: <%= Rails.application.credentials.development[:postgres_db] %>
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.0.12
    container_name: epam_music_redis_container
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: epam_music_pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epam_music_sidekiq_container
    depends_on:
      - web
      - postgres
      - redis
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
  mailcatcher:
    image: schickling/mailcatcher
    container_name: epam_music_mailcatcher_container
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - MAILCATCHER_PORT=1025
      - MAILCATCHER_HTTP_PORT=1080
    depends_on:
      - web
    links:
      - web
    networks:
      - default
volumes:
  db_data:
  pgadmin-data:
#  gem_cache:
#    external: true